language: python
python:
  - "3.7"
before_install:
  - pip install poetry
# command to install dependencies
install:
  - poetry install
# command to run tests
script:
  - poetry run flake8 .
  - poetry run pytest --cov=./quart_minify/ tests/
after_success:
  - poetry run coveralls
